### ISSUE TITLE
为什么没有发布到chrome应用市场

### ISSUE THREAD

**Issue by Jan9th** [xesam/android_offline_doc_plugin#1]
半年前经推荐用这个插件,虽然现在fq已经不是什么问题了,但是还是想问下有没有考虑过把它发布到chrome应用市场中去呢?记得之前用的时候开启开发者模式chrome浏览器会报警告,之后会修改该插件导致不可用.现在不知道是什么情况了.

**Comment by xesam** [comment]
官方的离线文档更新不及时，还是在线的比较靠谱，现在 google 开发者中文网站出来了之后，不翻墙也可以访问了。
